TaawonMVC.Web/Models/Building/BuildingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaawonMVC.Buildings.DTO;
using TaawonMVC.BuildingType.DTO;
using TaawonMVC.BuildingUnitContents.DTO;
using TaawonMVC.BuildingUnits.DTO;
using TaawonMVC.BuildingUses.DTO;
using TaawonMVC.Neighborhood.DTO;

namespace TaawonMVC.Web.Models.Building
{
    public class BuildingViewModel
    {
       public  IEnumerable<GetBuildingsOutput> Buildings { get; set; }
       public  GetBuildingsOutput Building { get; set; }
    // public  getNeighborhoodOutput neighborhood { get; set; }
       public  IEnumerable<GetBuildingTypeOutput> BuildingTypes { get; set; }
       public  IEnumerable<getNeighborhoodOutput> Neighborhoods { get; set; }
    // public  GetBuildingTypeOutput BuildingType { get; set; }
    // public  getNeighborhoodOutput Neighborhood { get; set; }
       public  SelectList YesOrNo { get; set; }
       public  string[] HoushNameArray { get; set; }
       public  IEnumerable<GetBuildingUsesOutput> BuildingUses { get; set; }
        //------to upload files 
        [Required(ErrorMessage = "Please select file.")]
        [Display(Name = "Browse File")]
        public HttpPostedFileBase[] files { get; set; }
        //-----------
        //create building units 
        public IEnumerable<GetBuildingUnitContentsOutput> BuildingUnitContents { get; set; }
        public GetBuildingUnitsOutput BuildingUnits { get; set; }
        //-----------------------
        //list of units in every building 
        public IEnumerable<GetBuildingUnitsOutput> BuildingUnitsOutputs { get; set; }


    }
}

TaawonMVC.Web/Models/Users/EditUserModalViewModel.cs
using System.Collections.Generic;
using System.Linq;
using TaawonMVC.Roles.Dto;
using TaawonMVC.Users.Dto;

namespace TaawonMVC.Web.Models.Users
{
    public class EditUserModalViewModel
    {
        public UserDto User { get; set; }

        public IReadOnlyList<RoleDto> Roles { get; set; }

        public bool UserIsInRole(RoleDto role)
        {
            return User.Roles != null && User.Roles.Any(r => r == role.Name);
        }
    }
}

TaawonMVC.Web/Controllers/BuildingController.cs
using Abp.Web.Mvc.Controllers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using TaawonMVC.Buildings;
using TaawonMVC.Buildings.DTO;
using TaawonMVC.BuildingType;
using TaawonMVC.BuildingType.DTO;
using TaawonMVC.BuildingUnitContents;
using TaawonMVC.BuildingUnits;
using TaawonMVC.BuildingUnits.DTO;
using TaawonMVC.Web.Models.Building;
using TaawonMVC.Models;
using TaawonMVC.Neighborhood;
using TaawonMVC.Neighborhood.DTO;
using TaawonMVC.BuildingUses;
using TaawonMVC.UploadFiles;
using TaawonMVC.UploadFiles.DTO;
using TaawonMVC.Web.Models.AntiForgery;

namespace TaawonMVC.Web.Controllers
{
    public class BuildingController : AbpController
    {
        private readonly IBuildingsAppService _buildingsAppService;
        private readonly IBuildingTypeAppService _buildingTypeAppService;
        private readonly INeighborhoodAppService _neighborhoodAppService;
        private readonly IBuildingUsesAppService _buildingUsesAppService;
        private readonly IUploadFilesAppService _uploadFilesAppService;
        private readonly IBuildingUnitContentsAppService _buildingUnitContentsAppService;
        private readonly IBuildingUnitsAppService _buildingUnitsAppService;
       
        public BuildingController(IBuildingsAppService buildingsAppService, IBuildingTypeAppService buildingTypeAppService, INeighborhoodAppService neighborhoodAppService, IBuildingUsesAppService buildingUsesAppService, IUploadFilesAppService uploadFilesAppService, IBuildingUnitContentsAppService buildingUnitContentsAppService, IBuildingUnitsAppService buildingUnitsAppService)
        {
            _buildingsAppService = buildingsAppService;
            _buildingTypeAppService = buildingTypeAppService;
            _neighborhoodAppService = neighborhoodAppService;
            _buildingUsesAppService = buildingUsesAppService;
            _uploadFilesAppService = uploadFilesAppService;
            _buildingUnitContentsAppService = buildingUnitContentsAppService;
            _buildingUnitsAppService = buildingUnitsAppService;

        }
        // GET: Building
        public ActionResult Index()
        {
            var getBuildingOutput = _buildingsAppService.getAllBuildings();
            // if neighborhood or buildingtype is deleted 
            // initiate the object with default values .
            foreach(var Building  in getBuildingOutput)
            {
                if(Building.BuildingType==null)
                {
                    Building.BuildingType = new TaawonMVC.Models.BuildingType();
                }
                if(Building.NeighboorHood==null)
                {
                    Building.NeighboorHood = new TaawonMVC.Models.Neighborhood();
                }

            }
            //get the list of buildingTypes
            var buildingTypes = _buildingTypeAppService.getAllBuildingtype().ToList();
            // get the list of neighborhoods
            var neighborhoods = _neighborhoodAppService.GetAllNeighborhood().ToList();
            // get the list of BuildingUses
            var buildingUses = _buildingUsesAppService.getAllBuildingUses().ToList();
            // get list of units 
            var buildingUnitsOutput = _buildingUnitsAppService.getAllBuildingUnits().ToList();

            //var BuildingTypeInput = new GetBuidlingTypeInput
            //{
            //    Id = id
            //};
            //var buildingType = _buildingTypeAppService.getBuildingTypeById(BuildingTypeInput);

            //populate yes-no list 
            var yesOrNo = new List<string>
            {
                "True",
                "False"
            };

            //Read HoushName From Database 
            //----------------------------
            var HoushNames = new List<string>();
            foreach(var HoushName in getBuildingOutput)
            {
                if (!String.IsNullOrWhiteSpace(HoushName.houshName))
                {
                    HoushNames.Add(HoushName.houshName);
                }
            }
            var HoushNameArray = HoushNames.ToArray();
            //foreach(var str in HoushNameArray)
            //{
            //    str.Trim();
            //    str.ToUpper();
            //}
            //var houshNameArrayClean = new string[HoushNameArray.Length];
            //for(int i=0;i< HoushNameArray.Length;i++)
            //{
            //    HoushNameArray[i].Trim();
            //    HoushNameArray[i].ToUpper();
            //    houshNameArrayClean[i] = HoushNameArray[i];
            //}
            // var HoushNameArrayWithoutDuplicate = new HashSet<string>(HoushNameArray);
            var HoushNameArrayWithoutDuplicate = HoushNameArray.Distinct().ToArray();

            //----------------------------
            //-----------------------------

            var BuildingsViewModel = new BuildingViewModel
            {
                Buildings = getBuildingOutput,
                BuildingTypes = buildingTypes,
                Neighborhoods=neighborhoods,
                Building = new GetBuildingsOutput(),
                YesOrNo= new SelectList(yesOrNo),
                HoushNameArray= HoushNameArrayWithoutDuplicate,
                BuildingUses=buildingUses,
                BuildingUnitsOutputs = buildingUnitsOutput






            };
            return View("Index",BuildingsViewModel);
        }


        public ActionResult EditBuildingModal(int userId)
        {
            //get the list of buildingTypes
            var buildingTypes = _buildingTypeAppService.getAllBuildingtype().ToList();
            // get the list of neighborhoods
            var neighborhoods = _neighborhoodAppService.GetAllNeighborhood().ToList();
           // get the list of building unit contents
            var buildingUnitContents = _buildingUnitContentsAppService.getAllBuildingUnitContents();
            // get list of buildings
            var getAllBuildingOutput = _buildingsAppService.getAllBuildings();
            // get the list of BuildingUses
            var buildingUses = _buildingUsesAppService.getAllBuildingUses().ToList();

            var getBuidlingsInput = new GetBuidlingsInput
            {
                Id = userId
            };

            var getBuildingOutput = _buildingsAppService.getBuildingsById(getBuidlingsInput);

            //Read HoushName From Database 
            //----------------------------
            var HoushNames = new List<string>();
            foreach (var HoushName in getAllBuildingOutput)
            {
                if (!String.IsNullOrWhiteSpace(HoushName.houshName))
                {
                    HoushNames.Add(HoushName.houshName);
                }
            }
            var HoushNameArray = HoushNames.ToArray();
            //foreach(var str in HoushNameArray)
            //{
            //    str.Trim();
            //    str.ToUpper();
            //}
            //var houshNameArrayClean = new string[HoushNameArray.Length];
            //for(int i=0;i< HoushNameArray.Length;i++)
            //{
            //    HoushNameArray[i].Trim();
            //    HoushNameArray[i].ToUpper();
            //    houshNameArrayClean[i] = HoushNameArray[i];
            //}
            // var HoushNameArrayWithoutDuplicate = new HashSet<string>(HoushNameArray);
            var HoushNameArrayWithoutDuplicate = HoushNameArray.Distinct().ToArray();

            //----------------------------
            //-----------------------------
            //populate yes or no select 
            var yesOrNo = new List<string>
            {
                "True",
                "False"
            };
            var BuildingViewModel = new BuildingViewModel
            {
                Building = getBuildingOutput,
                BuildingTypes=buildingTypes,
                Neighborhoods=neighborhoods,
                BuildingUnitContents = buildingUnitContents,
                BuildingUnits = new GetBuildingUnitsOutput(),
                HoushNameArray = HoushNameArrayWithoutDuplicate,
                YesOrNo = new SelectList(yesOrNo),
                BuildingUses = buildingUses


            };

            return View("_EditUserModal", BuildingViewModel);

        }
        //-----to upload files 
        public ActionResult UploadFiles()
        {
            return View();
        }

        [HttpPost]
        //[AllowAnonymous]
        // [Route("Building/EditBuildingModal")]
        //  [ValidateAntiForgeryToken]
        // [AjaxValidateAntiForgeryToken]
       // [ValidateAntiForgeryTokenOnAllPosts]
        public void UploadFiles(HttpPostedFileBase[] files, int BuildingId)
        {
            var UploadedFile = new CreateUploadFilesInput() ;
            //Ensure model state is valid
            if (ModelState.IsValid)
            {   //iterating through multiple file collection 
                foreach (HttpPostedFileBase file in files)
                {
                    //Checking file is available to save.
                    if (file != null)
                    {
                        //-----*** commited for not saving files to server ***-----
                        //var InputFileName = Path.GetFileName(file.FileName);
                        //var ServerSavePath = Path.Combine(Server.MapPath("~/UploadedFiles/") + InputFileName);
                        ////Save file to server folder
                        //file.SaveAs(ServerSavePath);
                        ////assigning file uploaded status to ViewBag for showing message to user.
                        ViewBag.UploadStatus = files.Count().ToString() + " files uploaded successfully.";

                        // convert file data (inputStream) to array byte[] in order
                        // to store it in database 
                        using (var binaryReader = new BinaryReader(file.InputStream))
                        {

TaawonMVC.Web/Views/Building/UploadFiles.cshtml
@model TaawonMVC.Web.Models.Building.BuildingViewModel
@{
    ViewBag.Title = "Upload Files";
}

@using (Html.BeginForm("UploadFiles", "Building", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.files, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.files, "", new { @type = "file", @multiple = "multiple" })
                @Html.ValidationMessageFor(model => model.files, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Upload" class="btn btn-primary" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 text-success">
                @ViewBag.UploadStatus
            </div>
        </div>

    </div>
}
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

TaawonMVC.Web/Views/Building/_EditUnitModal.cshtml
@using System.Web.Optimization
@using Abp.Authorization.Users
@using Abp.Web.Mvc.Extensions
@using TaawonMVC.Web.Models.Common.Modals
@model TaawonMVC.Web.Models.Building.BuildingViewModel
@{
    Layout = null;
}
@{
    SetAntiForgeryCookie();
}
@Html.Partial("~/Views/Shared/Modals/_ModalHeader.cshtml", new ModalHeaderViewModel(L("BuildingUnits")))

<div class="modal-body" id="EditDiv">

    <div class="tab-content">

        <table class="table">
            <thead>
                <tr>
                    <th>@L("ResidentName")</th>
                    <th>@L("ResidenceStatus")</th>
                    <th>@L("NumberOfFamilyMembers")</th>
                    <th>@L("Floor")</th>
                    <th>@L("Actions")</th>

                </tr>
            </thead>
            <tbody>


                @{

                    var BuildingUnits = Model.BuildingUnitsOutputs;

                }


                @foreach (var BuildingUnit in BuildingUnits)

                {
                    <tr>
                        <td>@BuildingUnit.ResidentName</td>
                        <td>@BuildingUnit.ResidenceStatus</td>
                        <td>@BuildingUnit.NumberOfFamilyMembers</td>
                        <td>@BuildingUnit.Floor</td>
                        <td class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">menu</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="#" class="waves-effect waves-block edit-BuildingUnit" data-BuildingUnit-id="@BuildingUnit.Id" data-toggle="modal" data-target="#UnitEditModal"><i class="material-icons">edit</i>@L("Edit")</a></li>
                                <li><a href="#" class="waves-effect waves-block delete-unit" data-BuildingUnit-id="@BuildingUnit.Id" data-BuildingUnit-name="@BuildingUnit.ResidentName"><i class="material-icons">delete_sweep</i>@L("Delete")</a></li>
                            </ul>
                        </td>
                    </tr>
                }

            </tbody>
        </table>






    </div>
</div>

@*@Html.Partial("~/Views/Shared/Modals/_ModalFooterWithSaveAndCancel.cshtml")*@
<div class="modal-footer">
    <button type="button" class="btn btn-default close-button waves-effect" data-dismiss="modal">@L("Cancel")</button>
</div>
<div class="modal fade" id="UnitEditModal" tabindex="-1" role="dialog" aria-labelledby="UserEditModalLabel" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">





        </div>
    </div>
</div>

<script src="~/Views/Building/Index.js"></script>